def main():
    build("Numbers.hs")
    build("Vectors.hs")
    build("EdgePlate.hs")
    build("Matrices.hs")
    build("Rotate.lhs", "-unlit")
    build("Geometric.hs")
    build("Preds.hs")
    build("Solve.hs")
    build("Cross.hs")
    build("Comparing.hs")
    build("Memo.hs")
    build("Postscript.hs")
    build("Hide.hs")
    build("MyIO.hs")
    build("Main.hs")
    run("Main")
