def main():
    build("Core_datatype.hs")
    build("Vtslib.hs")
    build("Sub_Core1.hs")
    build("Sub_Core2.hs")
    build("Sub_Core3.hs")
    build("Sub_Core4.hs")
    build("Dcore.hs")
    build("Core_database.hs")
    build("Kernel.hs")
    build("Type_defs.lhs", "-unlit")
    build("Edlib.lhs", "-unlit")
    build("Lookup.hs")
    build("X_interface.hs")
    build("Tree.hs")
    build("Token.lhs", "-unlit")
    build("Attributes.lhs", "-unlit")
    build("Unparse.lhs", "-unlit")
    build("Build_Tm.lhs", "-unlit")
    build("Build_itrm.lhs", "-unlit")
    build("Parse.lhs", "-unlit")
    build("Tags.hs")
    build("Globals.hs")
    build("Goals.hs")
    build("Tactics.hs")
    build("Parse.lhs", "-unlit")
    build("Auto.hs")
    build("Tacticals.hs")
    build("DerivedRules.hs")
    build("ThmTactics.hs")
    build("Display.hs")
    build("Editor.hs")
    build("Getops.hs")
    build("Main.hs")
    run("Main")
