#!/usr/bin/python

import sys

import yhc

def main(file):
    yhc.evaluate(yhc.evalfile(file).findFunction("main"))

if __name__ == "__main__":
    from yhc.options import options, args

    if options.profile:
        import profile
        profile.run("main('%s')" % (args[0], ))
    else:
        main(args[0])
